server {
    listen 3000;
    server_name localhost;

    location /api/directus/ {
        proxy_pass http://directus-v2bpvu6wqgna8fbsczs76x4n.89.42.199.190.sslip.io/;
        proxy_set_header Host directus-v2bpvu6wqgna8fbsczs76x4n.89.42.199.190.sslip.io;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Custom Error Pages
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }

    # Enable Gzip Compression for Fast Assets Delivery
    gzip on;
    gzip_vary on;
    gzip_min_length 10240;
    gzip_proxied any;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml application/javascript;
    gzip_disable "MSIE [1-6]\.";
}
